### ISSUE TITLE
Importing module throws exception

### ISSUE THREAD

**Issue by danielchipman** [PlayFab/MpsPowershell#2]
Running `Import-Module PlayFabMultiplayerApi` throws an exception in the 1.0.0 release of the module.

```
> Import-Module PlayFabMultiplayerApi
$RuntimeException/   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.Language.Compiler.NewOutputTypeAttribute(AttributeAst ast)
   at System.Management.Automation.Language.Compiler.GetAttribute(AttributeAst attributeAst)
   at System.Management.Automation.Language.ScriptBlockAst.<System-Management-Automation-Language-IParameterMetadataProvider-GetScriptBlockAttributes>d__68.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
   at System.Management.Automation.ScriptBlock.get_Attributes()
   at PlayFab.Multiplayer.Runtime.PowerShell.GetScriptCmdlet.<ProcessRecord>b__16_0(FunctionInfo fi)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PlayFab.Multiplayer.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()
Get-ScriptCmdlet : Unable to find type [PlayFab.Multiplayer.Models.IComponentsAf3SjfResponsesListbuildaliasesresponseContentApplicationJsonSchema].
At C:\Program Files\WindowsPowerShell\Modules\PlayFabMultiplayerApi\1.0.0\PlayFabMultiplayerApi.psm1:42 char:20
+     $cmdletNames = Get-ScriptCmdlet -ScriptFolder $exportsPath
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PlayFab.Multipl...ationJsonSchema:TypeName) [Get-ScriptCmdlet], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,PlayFab.Multiplayer.Runtime.PowerShell.GetScriptCmdlet```

**Comment by brianwp3000** [comment]
I'm having trouble reproducing this issue--could you try uninstalling and then reinstalling it? The following works for me in both Windows Powershell and Powershell Core:
```powershell
> uninstall-module playfabmultiplayerapi
> install-module playfabmultiplayerapi
> import-module playfabmultiplayerapi
```

**Comment by danielchipman** [comment]
This looks to be a caching issue with PowerShell ISE. Continued to repro for me, but I just restarted the session and it's gone, sorry for the false alarm.
